apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ include "mastodon.name" . }}-sidekiq
  name: {{ include "mastodon.name" . }}-sidekiq
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "mastodon.name" . }}-sidekiq
  template:
    metadata:
      labels:
        app: {{ include "mastodon.name" . }}-sidekiq
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox:latest
        command: ['sh', '-c', 
          'until nc -vz ${DB_HOST} ${DB_PORT}; do echo "Waiting for postgresql to be ready..."; sleep 3; done;
          until nc -vz ${REDIS_HOST} ${REDIS_PORT}; do echo "Waiting for redis to be ready..."; sleep 3; done;']
        env:
{{ include "mastodon.postgresql.path" . | indent 8 }}
{{ include "mastodon.redis.path" . | indent 8 }}
      containers:
      - image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
        name: {{ include "mastodon.name" . }}-sidekiq
        command: 
        - bash 
        - -c
        - "bundle exec sidekiq"
        env:
{{ include "mastodon.environment" . | indent 8 }}

