apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ include "mastodon.name" . }}-web
  name: {{ include "mastodon.name" . }}-web
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "mastodon.name" . }}-web
  template:
    metadata:
      labels:
        app: {{ include "mastodon.name" . }}-web
    spec:
      containers:
      - image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
        name: {{ include "mastodon.name" . }}-web
        env:
{{ include "mastodon.environment" . | indent 8 }}
