apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ include "mastodon.name" . }}-web
  name: {{ include "mastodon.name" . }}-web
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "mastodon.name" . }}-web
  template:
    metadata:
      labels:
        app: {{ include "mastodon.name" . }}-web
{{ include "mastodon.selectorLabels" . | indent 8 }}
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox:latest
        command: ['sh', '-c', 
          'until nc -vz ${DB_HOST} ${DB_PORT}; do echo "Waiting for postgresql to be ready..."; sleep 3; done;
          until nc -vz ${REDIS_HOST} ${REDIS_PORT}; do echo "Waiting for redis to be ready..."; sleep 3; done;']
        env:
{{ include "mastodon.postgresql.path" . | indent 8 }}
{{ include "mastodon.redis.path" . | indent 8 }}
      containers:
      - image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
        name: {{ include "mastodon.name" . }}-web
        command: 
        - bash 
        - -c
        - "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000"
        env:
{{ include "mastodon.environment" . | indent 8 }}
        ports:
        - containerPort: 3000
