apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-secrets-externalsecret
  namespace: mastodon
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore
  target:
    name: db-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: db-secrets-2
