apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "mastodon.name" . }}-init
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      restartPolicy: Never
      initContainers:
      - name: wait-for-db
        image: busybox:latest
        command: ['sh', '-c', 
          'until nc -vz ${DB_HOST} ${DB_PORT}; do echo "Waiting for postgresql to be ready..."; sleep 3; done;
          until nc -vz ${REDIS_HOST} ${REDIS_PORT}; do echo "Waiting for redis to be ready..."; sleep 3; done;']
        env:
{{ include "mastodon.postgresql.path" . | indent 8 }}
{{ include "mastodon.redis.path" . | indent 8 }}
      containers:
      - name: init-db-and-admin
        image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
        command: 
        - bash
        -  -c
        - |
          DISABLE_DATABASE_ENVIRONMENT_CHECK=1 RAILS_ENV=production rails db:setup; bundle exec rake db:migrate;
          bin/tootctl accounts create {{ .Values.initialAdmin.username }} --email {{ .Values.initialAdmin.email | default (printf "admin@%s" .Values.localDomain) }} --confirmed --approve --role Admin;
          echo Email: "{{ .Values.initialAdmin.email | default (printf "admin@%s" .Values.localDomain) }}"
        env:
{{ include "mastodon.environment" . | indent 8 }}

