image:
  tag: v4.3.6

redis:
    autoscaling:
      maxReplicas: 1
    replica:
      replicaCount: 0
    persistence:
      master:
        size: 2Gi
    auth:
      existingSecret: "db-secrets"
      existingSecretPasswordKey: "REDIS_PASSWORD"

postgresql:
    auth:
      database: "mastodon_production"
      username: "mastodon"
      existingSecret: "db-secrets"
      secretKeys:
        adminPasswordKey: POSTGRES_PASSWORD
        userPasswordKey: POSTGRES_PASSWORD
        replicationPasswordKey: POSTGRES_PASSWORD
