nameOverride: ""
localDomain: "mastodon.local"
existingEncriptionSecretName : "app-encription"
tlsSecretName: "mastodon-tls-secret"

web:
  image:
    tag: v4.3.6
    repository: tootsuite/mastodon

streaming:
  image:
    tag: v4.3.6
    repository: ghcr.io/mastodon/mastodon-streaming

sidekiq:
  image:
    tag: v4.3.6
    repository: tootsuite/mastodon


redis:
    autoscaling:
      maxReplicas: 1
    replica:
      replicaCount: 0
    persistence:
      master:
        size: 2Gi
    auth:
      existingSecret: "db-secrets"
      existingSecretPasswordKey: "REDIS_PASSWORD"
postgresql:
    auth:
      database: "mastodon_production"
      username: "mastodon"
      existingSecret: "db-secrets"
      secretKeys:
        adminPasswordKey: POSTGRES_PASSWORD
        userPasswordKey: POSTGRES_PASSWORD
        replicationPasswordKey: POSTGRES_PASSWORD
    primary:
      persistence:
        size: 3Gi
    readReplicas:
      persistence:
        size: 3Gi
