nameOverride: ""
localDomain: "t.akis.am"
certificateArn: "arn:aws:acm:us-west-2:418295714420:certificate/01125ef3-5dfa-487e-b498-19b32684973b"
existingEncriptionSecretName : "app-encription"
tlsSecretName: "mastodon-tls-secret"
initialAdmin:
  username: "mastodon"
  email: ""


web:
  image:
    tag: v4.3.6
    repository: tootsuite/mastodon

streaming:
  image:
    tag: v4.3.6
    repository: ghcr.io/mastodon/mastodon-streaming

sidekiq:
  image:
    tag: v4.3.6
    repository: tootsuite/mastodon


redis:
    global:
      defaultStorageClass: "gp2"
    autoscaling:
      maxReplicas: 1
    replica:
      replicaCount: 0
    persistence:
      master:
        size: 2Gi
    auth:
      existingSecret: "db-secrets"
      existingSecretPasswordKey: "REDIS_PASSWORD"
postgresql:
    global:
      defaultStorageClass: "gp2"
    auth:
      database: "mastodon_production"
      username: "mastodon"
      existingSecret: "db-secrets"
      secretKeys:
        adminPasswordKey: POSTGRES_PASSWORD
        userPasswordKey: POSTGRES_PASSWORD
        replicationPasswordKey: POSTGRES_PASSWORD
    primary:
      persistence:
        size: 3Gi
    readReplicas:
      persistence:
        size: 3Gi
