# {{- $svcName := printf "%s-web" (include "mastodon.name" .) -}}
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   creationTimestamp: null
#   name: {{ $svcName }}-ingress
# spec:
#   rules:
#   - host: ""
#     http:
#       paths:
#       - backend:
#           service:
#             name: {{ $svcName }}
#             port:
#               number: 3000
#         path: /
#         pathType: Prefix
#   tls:
#   - secretName: mastodon-tls-secret

